import type { Metadata } from "next";
import "./globals.css";
import { Julius_Sans_One } from "next/font/google";
import { ProductProvider } from "./ProductsContext";
import { ToastContainer } from 'react-toastify';


import AuthProvider from "./AuthContext";

const juliusSans = Julius_Sans_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-julius-sans",
});



export const metadata: Metadata = {
  title: "Uni Trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${juliusSans.variable} antialiased`}
      >
        <div
          className='w-full min-h-screen'>
          <ProductProvider>
            <AuthProvider>

              {children}
              <ToastContainer />
            </AuthProvider>
          </ProductProvider>
        </div>
      </body>
    </html>
  );
}
