import type { Metadata } from "next";
import "./globals.css";
import { Julius_Sans_One } from "next/font/google";
import { ProductProvider } from "./ProductsContext";
import { ToastContainer } from 'react-toastify';
import Navbar from "./components/home-components/Navbar";
import Footer from "./components/Footer";

const juliusSans = Julius_Sans_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-julius-sans",
});



export const metadata: Metadata = {
  title: "Uni Trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${juliusSans.variable} antialiased`}
      >
        <div
          className='w-full min-h-screen flex flex-col items-center justify-start'>
          <div className='px-4 py-2 max-w-[75vw] flex flex-col items-center justify-start gap-4 w-full'>
            <Navbar />
            <ProductProvider>
              {children}
              <ToastContainer />
            </ProductProvider>
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
