import React from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      className='w-full min-h-screen flex flex-col items-center justify-start'>
      <div className='px-4 py-2 max-w-7xl flex flex-col items-center justify-start gap-4 w-full'>
        <Navbar />

        {children}
      </div>
      <Footer />
    </div>
  )
}

export default layout
/**
 * import type { Metadata } from "next";
import "./globals.css";
import { Julius_Sans_One } from "next/font/google";
import { ProductProvider } from "./ProductsContext";
import { ToastContainer } from 'react-toastify';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AuthProvider from "./AuthContext";

const juliusSans = Julius_Sans_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-julius-sans",
});



export const metadata: Metadata = {
  title: "Uni Trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${juliusSans.variable} antialiased`}
      >
        <div
          className='w-full min-h-screen flex flex-col items-center justify-start'>
          <div className='px-4 py-2 max-w-7xl flex flex-col items-center justify-start gap-4 w-full'>
            <ProductProvider>
              <AuthProvider>
                <Navbar />

                {children}
                <ToastContainer />
              </AuthProvider>
            </ProductProvider>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}

 */